const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{pathToFileURL}=require('url');
const url=process.env.WAREHOUSE_URL||pathToFileURL(path.resolve('ETAK_Warehouse_3D.html')).href;
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await b.newPage({viewport:{width:1600,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.waitForFunction(()=>window.warehouse?.ready,null,{timeout:90000});
 assert.equal(await p.locator('.metrics').count(),0);assert.equal(await p.locator('h1').count(),0);assert.ok(await p.locator('#tourLaunch').isVisible());
 const state=await p.evaluate(()=>{warehouse.seek(0);return warehouse.getState()});assert.equal(state.forkliftCount,3);assert.equal(state.vehicles.length,3);assert.equal(state.staffCount,6);assert.equal(state.staff.length,6);assert.equal(state.walkingSpeed,8);assert.equal(state.tourSpeed,6.6);assert.equal(state.parkingColumns,0);assert.equal(state.brandBanner,true);assert.ok(state.doors.every(d=>d.open===0));
 const traffic=await p.evaluate(()=>{const hits=[],doors=[],loaded=new Set(),moved=Array.from({length:6},()=>new Set());for(let t=0;t<=300;t+=.2){const fleet=warehouse.sampleFleet(t),s=warehouse.getState();hits.push(...warehouse.operations.validateWalls().map(h=>({t,...h})));for(const [i,f] of s.staff.entries()){if(f.loaded)loaded.add(i);moved[i].add(f.x.toFixed(1)+','+f.z.toFixed(1));}for(const a of [...fleet,...s.staff])for(const d of s.doors){const u=Math.cos(d.rotation)*(a.x-d.x)-Math.sin(d.rotation)*(a.z-d.z),v=Math.sin(d.rotation)*(a.x-d.x)+Math.cos(d.rotation)*(a.z-d.z);if(Math.abs(u)<d.width/2&&Math.abs(v)<.5&&d.open<.94)doors.push({t,d:d.id});}}return {hits,doors,loaded:[...loaded],movement:moved.map(s=>s.size)};});assert.deepEqual(traffic.hits,[]);assert.deepEqual(traffic.doors,[]);assert.equal(traffic.loaded.length,6);assert.ok(traffic.movement.every(n=>n>10),'All six staff walk and move goods');
 const tours=[];for(const start of [0,65,170]){const r=await p.evaluate(start=>{warehouse.setView('overview',true);warehouse.seek(start);warehouse.operations.tour.start();let hits=0,doorHits=0,seconds=0;for(let i=0;i<12000;i++){seconds=i*.05;warehouse.operations.update(start+seconds,.05);const s=warehouse.getState(),w=s.walking;for(const r of [...warehouse.operations.staticWalls,...s.storageFootprints])if(w.x>r.x0+.01&&w.x<r.x1-.01&&w.z>r.z0+.01&&w.z<r.z1-.01)hits++;for(const d of s.doors){const u=Math.cos(d.rotation)*(w.x-d.x)-Math.sin(d.rotation)*(w.z-d.z),v=Math.sin(d.rotation)*(w.x-d.x)+Math.cos(d.rotation)*(w.z-d.z);if(Math.abs(u)<d.width/2&&Math.abs(v)<.3&&d.open<.94)doorHits++;}if(w.tour.status==='Tour complete')break;}return {start,seconds,hits,doorHits,tour:warehouse.operations.tour.state()};},start);assert.equal(r.tour.status,'Tour complete');assert.equal(r.hits,0);assert.equal(r.doorHits,0);tours.push({start,seconds:r.seconds,visited:r.tour.visited.length});}
 await p.evaluate(()=>{warehouse.setView('overview',true);warehouse.seek(20)});await p.selectOption('#languageSelect','en');assert.ok((await p.locator('#tourLaunch').textContent()).includes('4×'));await p.selectOption('#languageSelect','zh-Hant');assert.ok((await p.locator('#tourLaunch').textContent()).includes('4倍'));
 await p.locator('#tourLaunch').click();await p.locator('#autoTour').click();assert.equal(await p.evaluate(()=>warehouse.operations.tour.state().paused),true);await p.locator('#autoTour').click();await p.locator('#stopTour').click();await p.locator('#exitWalk').click();
 await p.locator('.door-details summary').click();await p.selectOption('#doorSelect','all');await p.locator('[data-door-mode="closed"]').click();await p.evaluate(()=>warehouse.seek(0));await p.waitForTimeout(300);assert.ok((await p.evaluate(()=>warehouse.getState().doors)).every(d=>d.open===0));await p.locator('[data-door-mode="auto"]').click();await p.locator('.door-details summary').click();
 for(const id of [1,6,14,16,17]){await p.selectOption('#cameraSelect',String(id));assert.ok(await p.locator('#referencePhoto').evaluate(e=>e.naturalWidth>0));}
 await p.evaluate(()=>{warehouse.setView('overview',true);warehouse.seek(20);});await p.screenshot({path:'overview.png'});await p.evaluate(()=>warehouse.setView('dock',true));await p.screenshot({path:'dock-view.png'});
 const mobile=await b.newPage({viewport:{width:390,height:844}});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(url);await mobile.waitForFunction(()=>window.warehouse?.ready,null,{timeout:90000});await mobile.locator('#menu').click();assert.ok(await mobile.locator('#tourLaunch').isVisible());assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth),390);await mobile.screenshot({path:'mobile-view.png'});await mobile.locator('#tourLaunch').click();assert.ok(await mobile.locator('#compactPause').isVisible());
 assert.equal(await mobile.locator('#walkStart').isVisible(),false);
 assert.ok((await mobile.locator('#walkPanel').boundingBox()).height<115);
 await mobile.locator('#compactPause').click();assert.equal(await mobile.evaluate(()=>warehouse.operations.tour.state().paused),true);
 await mobile.locator('#compactPause').click();assert.equal(await mobile.evaluate(()=>warehouse.operations.tour.state().paused),false);
 await mobile.locator('#walkCollapse').click();assert.ok(await mobile.locator('#autoTour').isVisible());
 await mobile.waitForTimeout(5200);assert.equal(await mobile.locator('#walkStart').isVisible(),false);
 await mobile.screenshot({path:'mobile-walking-view.png'});
 await mobile.locator('#exitWalk').click();
 await mobile.locator('#menu').click();await mobile.locator('[data-view="dock"]').click();assert.equal(await mobile.locator('#panel').isVisible(),false);
 await mobile.locator('#menu').click();assert.ok(await mobile.locator('#panel').isVisible());await mobile.waitForTimeout(5200);assert.equal(await mobile.locator('#panel').isVisible(),false);
 assert.deepEqual(errors,[]);const report={passed:true,url,errors,staff:6,forklifts:3,walkingSpeed:8,tourSpeed:6.6,wallHits:traffic.hits.length,closedDoorCrossings:traffic.doors.length,staffMovingAndWorking:traffic.movement,tours,primaryTourUI:true,branding:true,parkingColumns:0,mobile:true,languageSwitch:true};fs.writeFileSync('final-validation.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
