const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),{pathToFileURL}=require('node:url'),path=require('node:path');
const url=process.env.WAREHOUSE_URL||pathToFileURL(path.resolve('index.html')).href;
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await b.newPage({viewport:{width:1500,height:950}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.waitForFunction(()=>warehouse?.ready);
 const initial=await p.evaluate(()=>{warehouse.seek(0);return warehouse.getState()});assert.equal(initial.staff.length,8);assert.equal(initial.vehicles.length,4);assert.equal(await p.locator('.level').count(),0);assert.ok(initial.doors.every(d=>d.open===0));
 const traffic=await p.evaluate(()=>{
  const positions=Array.from({length:12},()=>new Set()),loaded=Array.from({length:8},()=>new Set()),cart=Array.from({length:8},()=>new Set()),wait=Array(12).fill(0),maxWait=Array(12).fill(0),doorHits=[],walls=[];let last=[];
  for(let t=0;t<180;t+=.1){const fleet=warehouse.sampleFleet(t),s=warehouse.getState(),actors=[...fleet,...s.staff];
   const h=warehouse.operations.validateWalls();if(h.length&&walls.length<5)walls.push({t,h});
   actors.forEach((a,i)=>{positions[i].add(a.x.toFixed(1)+','+a.z.toFixed(1));if(last[i]&&Math.hypot(a.x-last[i].x,a.z-last[i].z)<.001)wait[i]+=.1;else wait[i]=0;maxWait[i]=Math.max(maxWait[i],wait[i]);for(const d of s.doors){const u=Math.cos(d.rotation)*(a.x-d.x)-Math.sin(d.rotation)*(a.z-d.z),v=Math.sin(d.rotation)*(a.x-d.x)+Math.cos(d.rotation)*(a.z-d.z);if(Math.abs(u)<d.width/2&&Math.abs(v)<.3&&d.open<.94&&doorHits.length<5)doorHits.push({t,i,door:d.id});}});
   s.staff.forEach((a,i)=>{loaded[i].add(a.loaded);cart[i].add(a.withPalletTruck);});last=actors;
  }
  return {movement:positions.map(s=>s.size),loads:loaded.map(s=>[...s]),carts:cart.map(s=>[...s]),maxWait,doorHits,walls};
 });console.log('Traffic',JSON.stringify(traffic));assert.deepEqual(traffic.walls,[]);assert.deepEqual(traffic.doorHits,[]);assert.ok(traffic.movement.every(n=>n>20));assert.ok(traffic.maxWait.every(n=>n<4),'No idle groups');assert.ok(traffic.carts.slice(0,7).every(v=>v.length===2));assert.ok(traffic.loads.slice(0,7).every(v=>v.length===2));
 const layout=await p.evaluate(()=>{warehouse.seek(0);const ops=warehouse.operations,s=warehouse.getState();return {heights:[ops.floorHeight(36,16),ops.floorHeight(36,20),ops.floorHeight(36,27)],doors:s.doors.map(d=>d.id),w3Storage:s.storageFootprints.filter(r=>r.x0>=30.1&&r.z0<10),mist:s.coldMist};});assert.deepEqual(layout.heights,[.25,.25,.25]);assert.ok(layout.doors.includes('w2-w3')&&layout.doors.includes('w2-w1'));assert.deepEqual(layout.w3Storage,[]);assert.ok(layout.mist);
 const tours=[];for(const start of [0,35,90]){
  const tour=await p.evaluate(start=>{warehouse.setView('overview',true);warehouse.operations.reset();warehouse.seek(start);warehouse.operations.tour.start();const entry=warehouse.getState().walking;let hits=0,doorHits=0;for(let i=0;i<7000;i++){warehouse.operations.update(start+i*.04,.04);const s=warehouse.getState(),w=s.walking;for(const r of [...warehouse.operations.staticWalls,...s.storageFootprints])if(w.x>r.x0+.01&&w.x<r.x1-.01&&w.z>r.z0+.01&&w.z<r.z1-.01)hits++;for(const d of s.doors){const u=Math.cos(d.rotation)*(w.x-d.x)-Math.sin(d.rotation)*(w.z-d.z),v=Math.sin(d.rotation)*(w.x-d.x)+Math.cos(d.rotation)*(w.z-d.z);if(Math.abs(u)<d.width/2&&Math.abs(v)<.3&&d.open<.94)doorHits++;}if(w.tour.status==='Tour complete')return {seconds:i*.04,visited:w.tour.visited.length,hits,doorHits,entry:[entry.x,entry.z]};}return {failed:warehouse.getState().walking};},start);
  console.log('Tour',start,JSON.stringify(tour));assert.equal(tour.visited,14);assert.equal(tour.hits,0);assert.equal(tour.doorHits,0);assert.ok(tour.entry[0]>4.5&&tour.entry[0]<9&&tour.entry[1]<=2.1);tours.push(tour);
 }
 await p.evaluate(()=>{warehouse.setView('dock',true);warehouse.seek(18)});await p.screenshot({path:'v8-dock-view.png'});for(const id of [13,14]){await p.selectOption('#cameraSelect',String(id));await p.screenshot({path:`v8-c${id}-view.png`});}
 await p.selectOption('#languageSelect','en');await p.selectOption('#languageSelect','zh-Hant');
 const mobile=await b.newPage({viewport:{width:390,height:844}});await mobile.goto(url);await mobile.waitForFunction(()=>warehouse?.ready);const otherStarts=await mobile.evaluate(()=>{warehouse.seek(0);return warehouse.getState().staff.map(a=>[a.x,a.z]);});assert.notDeepEqual(otherStarts,initial.staff.map(a=>[a.x,a.z]));await mobile.locator('#menu').click();await mobile.locator('#tourLaunch').click();assert.ok(await mobile.locator('#compactPause').isVisible());assert.ok((await mobile.locator('#walkPanel').boundingBox()).height<115);await mobile.locator('#compactPause').click();await mobile.screenshot({path:'v8-mobile-view.png'});assert.deepEqual(errors,[]);
 const report={passed:true,url,layout,traffic,tours,errors};fs.writeFileSync('final-validation.json',JSON.stringify(report,null,2));console.log('PASS',JSON.stringify({layout,tours}));
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
