export let language='zh-Hant';
const zh={
 'Loading docks · flying to route start':'上落貨區 · 飛往導覽起點','Flying back to loading docks':'飛回上落貨區',
 'Loading docks → red route → loading docks':'上落貨區 → 紅線巡覽 → 上落貨區',
 'Frames per second':'每秒影格',
 'Red route start':'紅線起點（西南面）','Red route end':'紅線終點（南面出貨區）','W3 loading dock':'W3 上落貨區','North freezer turnaround':'北面冷凍庫折返點','North freezer return aisle':'北面冷凍庫回程','Cold room passage':'冷藏與冷凍庫連接通道','Frozen room cross aisle':'冷凍庫橫向通道','Frozen room turnaround':'冷凍庫折返點','Frozen room return aisle':'冷凍庫回程','Frozen room, east return':'冷凍庫東面出口','South loading area exit':'南面上落貨區出口',
 'Northwest empty area':'西北面空置區','Northwest cross aisle':'西北面橫向通道','Walking to next task':'步行前往工作位置','W2 / W3 rapid door':'W2／W3 快速門','W2 / W1 rapid door':'W2／W1 快速門','W3 / LOADING DOCK':'W3／上落貨區',
 'NORTH DISPATCH · W3':'北面出貨區 · W3','North dispatch door':'北面出貨區門','W2 · CHILLED / 4–10°C':'W2 · 冷藏區 / 4–10°C','W6 · CHILLED / 4–10°C':'W6 · 冷藏區 / 4–10°C','Open connection to W6':'開放連通 W6','Open connection to W2':'開放連通 W2','W2 chilled area, north':'W2 冷藏區北端','W2 chilled area, south':'W2 冷藏區南端',
 'Show walking controls':'展開步行控制','Hide walking controls':'收合步行控制','Stepping aside for traffic':'移至旁邊讓車先行',
 'Follow the red route · 4× walking speed':'沿紅線全倉巡覽 · 4倍步行速度','VIEWPOINTS':'選擇視角','DISPLAY OPTIONS':'顯示選項',
 'Start auto tour':'開始自動導覽','Pause tour':'暫停導覽','Resume tour':'繼續導覽','Stop tour':'停止導覽','Auto tour · whole warehouse':'自動導覽 · 全倉巡覽','Auto walking':'自動步行中','Waiting for clear route':'等候通道暢通','Waiting for door or traffic':'等候開門或讓路','Tour complete':'全倉導覽完成','Southwest staging':'西南面作業區','Indoor truck apron':'室內貨車停泊區','North freezer cross aisle':'北面冷凍庫橫向通道','NORTH FROZEN / −18°C':'北面冷凍庫 / −18°C','−18°C / insulated frozen storage':'−18°C / 保溫冷凍儲存區',

 'ETAK · Warehouse in motion':'ETAK · 倉庫動態模型','LOGISTICS / SPATIAL STUDY':'物流倉庫 / 空間模型','ATL · A1 EAST / PHOTO-MATCHED':'亞洲貨櫃物流中心 · A1東翼 / 實景重建','LIVE SIMULATION':'動態模擬','Controls':'控制選單',
 'WAREHOUSE / RECONSTRUCTED':'倉庫 / 實景重建','The real layout.':'真實佈局。','A clearer view.':'清晰呈現。','Traced storage blocks. Photo-matched details. A clean, working warehouse.':'依照平面圖及實景照片，呈現整齊有序的倉庫運作。',
 'STOCKED STORAGE POSITIONS':'儲存位置使用率','PALLETS VISUALIZED':'模型內的貨板','ACTIVE FORKLIFTS':'運作中的鏟車','TRUCK APRON LEVEL':'貨車停泊區標高',
 'Rack and stack organization follows the detailed plan. Aisles and loading docks are kept orderly and clear.':'貨架及貨板依詳細平面圖排列，通道與上落貨區保持暢通。','North frozen zone':'北面冷凍區','Mapped cold-room racking':'按圖配置的冷庫貨架','Clear dispatch & circulation':'暢通的出貨區與通道',
 'MATCH A CCTV VIEW':'對照閉路電視視角','Choose C01–C27…':'選擇 C01–C27…','24 cameras with photos · 3 plan-only locations':'24個鏡頭附照片 · 3個僅按圖定位','EXPLORE THE SPACE':'探索倉庫',
 '01 · Overview':'01 · 全景','02 · Plan view':'02 · 平面俯視','03 · Loading docks':'03 · 上落貨區','04 · In the aisles':'04 · 貨架通道','Follow a forklift ↗':'跟隨鏟車 ↗','Walk as a person':'第一身步行',
 'Labels':'標示','Roof':'屋頂','Floor plan ↗':'平面圖 ↗','Cameras':'鏡頭','ON THE WAREHOUSE FLOOR':'倉庫現場動態','Pallets picked from storage, carried through clear aisles, and placed inside trailers.':'鏟車及員工手唧車沿通道搬運貨物，在門開啟後通行並裝入貨車。',
 'Warehouse floor → trailer bed':'倉庫地面 → 貨車車斗','Truck pavement at −1.50 m':'貨車停泊路面低1.50米','Based on the detailed rack plan and 28 Sep CCTV.':'依詳細貨架圖及9月28日閉路電視照片重建。','Clean reconstruction; camera heights and hidden details are estimated.':'整齊化重建；鏡頭高度與遮蔽細節為估算。',
 'Drag to orbit':'拖曳旋轉','Scroll to zoom':'滾輪縮放','Right-drag to pan':'右鍵拖曳平移','Warehouse operations':'倉庫搬運作業','Speed':'速度','Reset view':'重設視角','Pause simulation':'暫停模擬','Play simulation':'播放模擬',
 'The detailed storage & CCTV plan':'詳細貨架及閉路電視位置圖','Close ✕':'關閉 ✕','Source floor plan':'原始平面圖','ETAK Logistics ATL A1 East wing floor plan':'ETAK 亞洲貨櫃物流中心 A1東翼平面圖',
 'Warehouse2025 1030.pdf establishes rack blocks and C01–C27 positions. The earlier dimensioned plan anchors the scale. Blue C-arrows are camera viewpoints; red cable runs and W annotations are omitted from the model. Photo references refine materials and storage types; clutter is intentionally tidied.':'貨架與 C01–C27 位置依 Warehouse2025 1030.pdf 配置，尺寸參考原有標註圖。藍色箭頭代表鏡頭方向；3D模型略去紅色電纜及 W 標記。上方長條儲存區為冷凍區，實景中的雜物已整理。',
 'CCTV REFERENCE':'閉路電視實景對照','Close CCTV view':'關閉閉路電視視角','CCTV reference photograph':'閉路電視參考照片','No reference image supplied for this camera.':'此鏡頭未提供參考照片。','Original reference · click to enlarge':'原始參考照片 · 點擊放大','Next image':'下一張照片','Plan arrows guide the views. Lens positions are adjusted inside rooms; heights, lens angles and hidden details are estimated.':'視角參考圖上箭頭，鏡頭位置微調至室內。高度、視角及遮蔽細節為估算。','CCTV reference / 28 September 2026':'閉路電視參考 / 2026年9月28日','Enlarged CCTV reference':'放大的閉路電視參考照片','Building the warehouse':'正在建立倉庫模型','Preparing materials, storage and moving equipment…':'正在載入材質、貨物及搬運設備…','Interactive 3D warehouse model':'互動3D倉庫模型',
 'Continuous loading cycle':'循環搬運作業','pallets dispatched':'板貨已出貨','Picking pallet':'提取貨板','To dispatch':'前往上落貨區','Loading trailer':'裝貨中','Returning empty':'空車返回','Next collection':'準備下一板貨','Waiting for door':'等候開門','Waiting for traffic':'等候通道暢通','Collecting':'準備搬運','Pallet truck loading':'手唧車裝貨','Pushing pallet truck':'推送手唧車','Loading by hand':'員工裝貨中',
 'DOOR CONTROL':'快速門控制','Automatic':'自動感應','Open':'開啟','Close':'關閉','All doors':'全部門','Door status':'門的狀態','Opening':'開門中','Closing':'關門中','Closed':'已關閉','Safety hold':'通行中，暫緩關門','Doors open for approaching people and vehicles. Closing waits until the opening is clear.':'有人或車輛接近時自動開門。門洞有人或車輛時暫緩關閉。',
 'North freezer door':'北面冷凍區門','East handling door':'東面搬運區門','South dispatch door':'南面出貨門','Chilled north door':'冷藏庫北門','Chilled south door':'冷藏庫南門','Frozen link door':'冷凍庫連接門','Cold-room connecting door':'冷庫連通門',
 'Walking view':'第一身步行','Drag to look · WASD / arrows to walk · E to operate a nearby door · Esc to exit':'拖曳環顧 · WASD／方向鍵步行 · E 操作附近的門 · Esc 離開','Start location':'起步位置','South aisle':'南面貨架通道','North ramp / C16':'北面人行斜坡 / C16','South ramp / C17':'南面人行斜坡 / C17','North freezer':'北面冷凍區','Exit walking':'離開步行','Forward':'向前','Back':'向後','Left':'向左','Right':'向右','Walking is blocked by walls, racks and closed doors.':'牆身、貨架及關閉的門會阻擋步行。',
 'NORTH FROZEN':'北面冷凍區','Frozen storage / north–south lanes':'冷凍儲存 / 南北向排列','FROZEN':'冷凍庫','−18°C / mapped rack blocks':'−18°C / 按圖配置貨架','CHILLED':'冷藏庫','4–10°C / perimeter racks':'4–10°C / 沿牆貨架','SOUTH RACK AISLE':'南面貨架通道','NORTH DISPATCH':'北面出貨區','Clear rapid-door lobby':'快速門前室 / 保持暢通','SOUTH DISPATCH':'南面出貨區','Clear loading area':'上落貨區 / 保持暢通','INDOOR TRUCK APRON':'室內貨車停泊區','Pavement −1.50 m':'路面低1.50米','NORTH STAFF RAMP':'北面員工斜坡','SOUTH STAFF RAMP':'南面員工斜坡','C16 / pedestrian access':'C16 / 員工出入口','C17 / pedestrian access':'C17 / 員工出入口',
 'SERVICE CORE':'服務設施','ELECTRICAL / SERVICES':'電力及設備','KEEP CLEAR':'保持暢通','DISPATCH':'出貨區','FIRE':'消防','CROSS AISLE / KEEP CLEAR':'橫向通道 / 保持暢通','FROZEN / −18°C':'冷凍庫 / −18°C','FROZEN  /  −18°C':'冷凍庫 / −18°C','CHILLED / 4–10°C':'冷藏庫 / 4–10°C','CHILLED  /  4–10°C':'冷藏庫 / 4–10°C','CHILLED / EXIT':'冷藏庫出口','INSULATED SLIDING DOOR':'隔熱門','STAFF EXIT':'員工出口','WATCH YOUR STEP':'小心斜坡','ETAK  /  COLD CHAIN':'ETAK / 冷鏈運輸','ETAK LOGISTICS':'ETAK 物流','ETAK  /  ATL A1 EAST':'ETAK / ATL A1東翼',
 'South rack aisle':'南面貨架通道','South rack aisle, reverse':'南面貨架通道（反向）','South dispatch entrance':'南面出貨入口','South loading area':'南面上落貨區','Chilled room, south':'冷藏庫南端','Chilled room, north':'冷藏庫北端','Frozen room, east':'冷凍庫東端','Frozen room, north':'冷凍庫北端','East handling aisle, south':'東面搬運通道南端','East handling aisle, north':'東面搬運通道北端','Main cross aisle, west view':'冷凍區橫向通道（向西）','Main cross aisle, east view':'冷凍區橫向通道（向東）','North rapid-door lobby':'北面快速門前室','North dispatch lobby':'北面出貨前室','North blue rapid door':'北面藍色快速門','North personnel exit':'北面員工出口','South personnel exit':'南面員工出口','Truck apron, south outward':'貨車區南端（向外）','South refrigerated truck':'南面冷凍貨車','Apron, northward':'貨車區（向北）','Apron, southward':'貨車區（向南）','North refrigerated trucks':'北面冷凍貨車','North apron panorama':'北面貨車區全景','Northwest service corridor':'西北面服務通道','South apron panorama':'南面貨車區全景','North apron outward':'北面貨車區（向外）','South apron outward':'南面貨車區（向外）','plan only':'僅按圖定位','Plan location only · no matching photo supplied':'僅按圖定位 · 未提供對應照片','C04, C07 and C08 are located from the plan, without a supplied image.':'C04、C07及C08依平面圖定位，未提供相應照片。'
};
export const tr=s=>language==='zh-Hant'?(zh[s]||s):s;
const nodes=[],attrs=[],listeners=[];
export const onLanguage=fn=>listeners.push(fn);
export function initLanguage(){
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;
 while(n=walker.nextNode()){if(['SCRIPT','STYLE'].includes(n.parentElement?.tagName))continue;const text=n.nodeValue.trim();if(zh[text])nodes.push([n,n.nodeValue,text]);}
 for(const el of document.querySelectorAll('[aria-label],[alt]'))for(const name of ['aria-label','alt']){const value=el.getAttribute(name);if(value&&zh[value])attrs.push([el,name,value]);}
 document.getElementById('languageSelect').onchange=e=>setLanguage(e.target.value);
 setLanguage('zh-Hant');
}
export function setLanguage(value){language=value==='en'?'en':'zh-Hant';document.documentElement.lang=language;document.title=tr('ETAK · Warehouse in motion');for(const [n,raw,key] of nodes)n.nodeValue=raw.replace(key,tr(key));for(const [el,name,key] of attrs)el.setAttribute(name,tr(key));document.getElementById('languageSelect').value=language;listeners.forEach(fn=>fn());}
